POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "unico rq",
    "number": 321231
}

### Heroku
POST https://glacial-stream-15944.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Pablo en MongoDb",
    "number": 321231
}